apiVersion: v1
kind: Service
metadata:
  name: vaccination-service
spec:
  type: NodePort
  selector:
    app: vaccination-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30006
